# Generated by Django 2.2.16 on 2022-12-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20221218_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='code',
            new_name='color',
        ),
    ]
