# Generated by Django 2.2.16 on 2022-12-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0005_auto_20221218_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmount',
            new_name='RecipeIngredient',
        ),
    ]
