# Generated by Django 2.2.16 on 2022-12-06 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0002_auto_20221205_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopList',
            new_name='ShoppingList',
        ),
    ]
